#+TITLE: CS345 Homework 1
#+AUTHOR: Parker Gabel
#+LATEX_CLASS: article
#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}
#+LATEX_COMPILER: pdflatex
#+DATE: \today
#+OPTIONS: toc:nil
* A coin is flipped 10 times in a row.
** How many possible results are there? 
   There are 2 possible results for any individual coin flip. Since there are 10 flips there are 2^10 possible sequences.
** How many of those results have exactly four heads?
   The answer is how many ways can exactly four heads be arranged in a sequece of ten choices.
   \[
       \binom{10}{4} = 210
   \]
** How many results have the same number of heads as tails?
   It is sufficient to find the number of ways to arrange five heads.
   \[
       \binom{10}{5} = 252
   \]
* How many cards must be chosen from a standard deck of 52 cards to guarantee a pair of matching values is chosen?
  Notice there are 13 possible cards, ignoring suit. So in the worst case scenario you draw 13 cards and all are different then the 14^th card is guaranteed to match a previous card drawn. So the answer is 14.
* Suppose that on an island there are two types of people, knights and knaves. Knights always tell the truth and knaves always lie. You meet three people from the island, Bilbo, Frodo, and Sam. If Bilbo says “I am a knave and Frodo is a knight” and Frodo says “Exactly one of the three of us is a knight”. Can you tell what Bilbo, Frodo, and Sam are? If so, what are they. Explain your answer.
  Notice in order for Bilbo's statement to be true both parts of the and expression must be true. Assume Bilbo is a Knight. The first part of Bilbo's expression("I am a Knave") is false so the whole expression is false. Thus Bilbo cannot be a Knight. Now assume Bilbo is a Knave. Since Bilbo's statement must be false and the first part of the expression is true, the second part("Frodo is a knight") must be false. 
  So Frodo is knave. So frodo's statement must be false. So there cannot be exactly one Knight. Since Bilbo and Frodo are known to be knaves, Sam must also be a knave.  
* Now suppose that in addition to knights and knaves, the island from problem 3 also contains normals who may lie or tell the truth. Suppose a crime was committed and you have three suspects, John, Paul and George. You know the crime was committed by a knight. You know exactly one of your three suspects is a knight. You also have this transcript: Paul: “I am innocent.”John: “What Paul says is true.” George: “John is not normal.” Who is the guilty person? Explain your reasoning.
  If Paul is a Knight then his statement is true but he is guilty so that is false. So Paul cannot be a Knight. If Paul is a Knave then his statement is false so he must be a guilty. However we know a Knight is guilty so that cannot be the case. So Paul is not a Knave. So Paul is a normal.
  If John is a Knave then what Paul says must be false. So Paul is guilty. However, we know that Paul is a normal so that cannot be the case. If John is normal then George must be the Knight. However George's statement must be true but it would be false. So George cannot be the Knight. Thus the only remaing option for the Knight is John. Sir John is our dastardly villain.
* Prove: 1×2^0 + 2×2^1 + 3×2^2 + . . . + n×2^n^-1 = (n – 1)×2^n + 1
  Proof by induction.
  Let P(x) be the statement \[1\times2^0 + 2\times2^1 + 3\times2^2 + . . . + n\times2^{{x-1}} = (x - 1)\times2^x + 1\]
  Base Case: P(1) is true.
\begin{proof}
\[P(1) = 1\times2^0 = (1 \minus 1)\times2^1 \plus 1 = 1\]
Thus P(1) is true.
\end{proof}
  Inductive Step: If P(k) is true then P(k+1) is true
\begin{proof}
Assume P(k) is true. So \[1\times2^0 + 2\times2^1 + 3\times2^2 + . . . + k\times2^{{k-1}} = (k - 1)\times2^k + 1\]
Consider \[1\times2^0 + 2\times2^1 + 3\times2^2 + . . . + k\times2^{{k-1}} \plus (k \plus 1)\times2^k = (k - 1)\times2^k + 1 \plus (k \plus 1)\times2^k\]
So \[(k - 1)\times2^k \plus 1 \plus (k\plus1)\times2^k = (k \plus k \plus 1 \minus 1)\times2^k \plus 1 = (2 \times k)\times2^k + 1 = k\times2^{k+1} + 1 = ((k + 1) -1)\times2^k + 1\]
So P(k+1) is true.
\end{proof}
